/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'otherElectricalWork' : IDL.Null,
  'tvPoint' : IDL.Null,
  'fanFitting' : IDL.Null,
  'maintenance' : IDL.Null,
  'geyser' : IDL.Null,
  'wiringContract' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const BookingRequestInput = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getBookingRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BookingRequest)],
      ['query'],
    ),
  'getBookingRequestsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitBookingRequest' : IDL.Func([BookingRequestInput], [IDL.Nat], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'otherElectricalWork' : IDL.Null,
    'tvPoint' : IDL.Null,
    'fanFitting' : IDL.Null,
    'maintenance' : IDL.Null,
    'geyser' : IDL.Null,
    'wiringContract' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const BookingRequestInput = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getBookingRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BookingRequest)],
        ['query'],
      ),
    'getBookingRequestsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitBookingRequest' : IDL.Func([BookingRequestInput], [IDL.Nat], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };