/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface BookingRequestInput {
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type ServiceType = { 'otherElectricalWork' : null } |
  { 'tvPoint' : null } |
  { 'fanFitting' : null } |
  { 'maintenance' : null } |
  { 'geyser' : null } |
  { 'wiringContract' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getBookingRequest' : ActorMethod<[bigint], [] | [BookingRequest]>,
  'getBookingRequestsByStatus' : ActorMethod<
    [BookingStatus],
    Array<BookingRequest>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitBookingRequest' : ActorMethod<[BookingRequestInput], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];