/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface BookingRequestInput {
    serviceType: ServiceType;
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface BookingRequest {
    id: bigint;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ServiceType {
    otherElectricalWork = "otherElectricalWork",
    tvPoint = "tvPoint",
    fanFitting = "fanFitting",
    maintenance = "maintenance",
    geyser = "geyser",
    wiringContract = "wiringContract"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllBookingRequests(): Promise<Array<BookingRequest>>;
    getBookingRequest(bookingId: bigint): Promise<BookingRequest | null>;
    getBookingRequestsByStatus(status: BookingStatus): Promise<Array<BookingRequest>>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    submitBookingRequest(input: BookingRequestInput): Promise<bigint>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
}
import type { BookingRequest as _BookingRequest, BookingRequestInput as _BookingRequestInput, BookingStatus as _BookingStatus, ServiceType as _ServiceType, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllBookingRequests(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingRequest(arg0: bigint): Promise<BookingRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingRequest(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingRequest(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingRequestsByStatus(arg0: BookingStatus): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingRequestsByStatus(to_candid_BookingStatus_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingRequestsByStatus(to_candid_BookingStatus_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitBookingRequest(arg0: BookingRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingRequest(to_candid_BookingRequestInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingRequest(to_candid_BookingRequestInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingRequest]): BookingRequest | null {
    return value.length === 0 ? null : from_candid_BookingRequest_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    serviceType: _ServiceType;
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
}): {
    id: bigint;
    status: BookingStatus;
    serviceType: ServiceType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n6(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n8(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    otherElectricalWork: null;
} | {
    tvPoint: null;
} | {
    fanFitting: null;
} | {
    maintenance: null;
} | {
    geyser: null;
} | {
    wiringContract: null;
}): ServiceType {
    return "otherElectricalWork" in value ? ServiceType.otherElectricalWork : "tvPoint" in value ? ServiceType.tvPoint : "fanFitting" in value ? ServiceType.fanFitting : "maintenance" in value ? ServiceType.maintenance : "geyser" in value ? ServiceType.geyser : "wiringContract" in value ? ServiceType.wiringContract : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n4(_uploadFile, _downloadFile, x));
}
function to_candid_BookingRequestInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequestInput): _BookingRequestInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: ServiceType;
    name: string;
    email: string;
    message: string;
    phone: string;
}): {
    serviceType: _ServiceType;
    name: string;
    email: string;
    message: string;
    phone: string;
} {
    return {
        serviceType: to_candid_ServiceType_n17(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    otherElectricalWork: null;
} | {
    tvPoint: null;
} | {
    fanFitting: null;
} | {
    maintenance: null;
} | {
    geyser: null;
} | {
    wiringContract: null;
} {
    return value == ServiceType.otherElectricalWork ? {
        otherElectricalWork: null
    } : value == ServiceType.tvPoint ? {
        tvPoint: null
    } : value == ServiceType.fanFitting ? {
        fanFitting: null
    } : value == ServiceType.maintenance ? {
        maintenance: null
    } : value == ServiceType.geyser ? {
        geyser: null
    } : value == ServiceType.wiringContract ? {
        wiringContract: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
